### ISSUE TITLE
Add ability to Edit Entry or Page without needing to change Required Asset field

### ISSUE THREAD

**Issue by bgarrant** [statamic/workshop#15]
**Is your feature request related to a problem? Please describe.**
Using latest Statamic 2.9.8 and Workshop 1.1.0, when you create an Edit form with a required Asset field you cant update without having to upload the asset again or a new one. If you want to keep the same Asset and make the field required, how can we do this? Sometimes you just need to update a text field and not the Asset field, so this would be very helpful.

**Describe the solution you'd like**
It would be great to be able to Edit an Entry or Page and have an Asset required without be forced to  upload a new Asset

**Describe alternatives you've considered**
Maybe a hidden field with the Asset value could be passed back when saved if not changed?

**Additional context**
None

**Comment by bgarrant** [comment]
If the Asset field is not required, it seems to keep the existing value fine on save.  But there are times when we need to have an asset required.  When you make it required it will not allow Save without uploading a new image.

![screen shot 2018-07-17 at 6 19 01 am](https://user-images.githubusercontent.com/2436728/42811689-5ebb6fd8-8989-11e8-8db7-028f1d972033.png)

**Comment by dannyuk1982** [comment]
So at the moment it's not possible to have a required asset field, without re-uploading every time? I think that is needed functionality personally. Can it not have some extra logic along the lines of: if required then either upload a file or if there is one and no uploaded file then keep this?

**Comment by danielfowler** [comment]
@bgarrant it's interesting to me.... if this is for an EDIT form, and the image is required, wouldn't it already have an image? So when editing, the field doesn't need to be required, does it? As long as you don't have a _Remove Existing Image_ option, you should always be satisfied with the existing image or the (optional) newly uploaded image. No?

**Comment by bgarrant** [comment]
@danielfowler I agree.  But if you make the fields required for the Asset for INSERT form, how do you disable it just for the EDIT form?  I do not know how to do that and I do not think there is a way.

**Comment by dannyuk1982** [comment]
You would usually use the same form for editing and adding surely? Having to make 2 forms with the only difference being that one field is required and the other isn't, isn't very DRY

**Comment by danielfowler** [comment]
I beg to differ. To expedite onboarding, a simple CREATE form that only asks for title, location is a great way to reduce friction. Then my edit forms are more robust.
  

  
But if you have the luxury of a captive audience and you have the same add/edit form, your URL is surely different right? So use something like ‘{{ unless segment_3==“edit” }}required{{ /unless }}’ to do it dynamically.
  

  
If you’re not using unique URLs, throw in a parameter, like   ‘{{ unless get:mode==“edit” }}required{{ /unless }}’
  
  
  
 Cheers!
  
  
  
  
---
  Daniel Fowler   
Digital Project Leadership
  
Fowlertown.com
  
Cast98.com
  
DraftySports.com
  

  
Sent from my iPhone; please excuse any spelling or contextual errors.
  
  
  
  
  

  
  
>

**Comment by dannyuk1982** [comment]
My use case is people managing their listing on a directory site - so they need to fill out all the fields from the outset, their listing is no use only with half the fields. So yea.. same form for both, there needs to be an image at all times.

**Comment by bgarrant** [comment]
Something like this per field would also be cool...
```
{{ field.render({
    class: "freeform-input",
    labelClass: "freeform-label" ~ (field.required ? " freeform-required" : ""),
    errorClass: "freeform-errors",
    instructionsClass: "freeform-instructions",
    instructionsBelowField: true,
    overrideValue: "This is now the new default value",
    inputAttributes: {
        "data-field-id": field.id,
    }
}) }}
```

**Comment by danielfowler** [comment]
I put together some simple vanilla JS in a Codepen to show [how you can add/remove required upload fields](https://codepen.io/danielfowler/pen/LBXERz) so that a user doesn't have to replace something that's already there, but you can require the field if they opt in to replacing it. Maybe you'll find it useful.

**Comment by bgarrant** [comment]
I will check that out @danielfowler .  Thanks as always

**Comment by bgarrant** [comment]
@danielfowler So if I have the field required in the CP which I need for the site editors, then I use the code you posted in the CMS for my workshop Edit form I am still getting the error when I do not change an image and try to save.

![screen shot 2018-08-10 at 12 56 31 pm](https://user-images.githubusercontent.com/2436728/43970876-006a7056-9c9d-11e8-97ee-19232c1f553e.png)

```
              <script>
                // INTENDED FOR USE WITH STATAMIC WORKSHOP

                // each upload field will be required
                // remove square brackets from name attribute if only one upload should be allowed
                var uploadHTML = 
                '<input type="file" name="event_image" required/>' +
                '<button class="button small alert" onclick="removeUploadInput(this)">Remove</button>';

                function addUploadInput(el) {
                var parent = el.parentNode
                var upload = document.createElement('div')
                upload.classList.add('upload-item')
                upload.innerHTML = uploadHTML
                parent.appendChild(upload)

                // use this if only one uploadable item should be allowed
                addButton = el
                addButton.style.display = 'none'
                }

                function removeUploadInput(el) {
                var parent = el.parentNode
                parent.remove()

                // use this if only one uploadable item should be allowed
                addButton.style.display = 'block'
                }
              </script>
<button class="button small green" onclick="addUploadInput(this)">Change Event Hero Image</button>
```

**Comment by danielfowler** [comment]
Yeah, you need to not require it in CP (it'll still be required by the HTML code).

**Comment by bgarrant** [comment]
Yeah the CP needs it requires so the other users have it requires as well. That is the issue I have been having. The edit form requires an upload even when none is needed. Need it to work like it does in the CP.

**Comment by jasonvarga** [comment]
Here's a way you can maintain an existing asset when editing a form without needing to upload a new one. It works even if the field is required.

```
{{ workshop:entry:edit files="true" }}

    {{ errors | ul }}

    Title:
    <input type="text" name="title" value="{{ old:title or title }}">

    Image:
    <input type="hidden" name="image" value="{{ image }}">
    <input type="file" name="image">
	
    <button>Submit</button>

{{ /workshop:entry:edit }}
```

Put a hidden field containing the existing value _before_ your file field.
If you leave the file field blank, the hidden field will be submitted.
If you choose something in your file field, it will override the hidden field.

This is the same concept that people use with checkboxes.
Leaving a checkbox unchecked would submit nothing. If you actually want a false value to come through, you'd put a hidden field with the falsey value before the checkbox.

**Comment by bgarrant** [comment]
This works great Jason.  Thanks!

**Comment by bgarrant** [comment]
This does not work when using multiple images.  Please see https://github.com/statamic/workshop/issues/20
