### ISSUE TITLE
Workshop Docs href bug

### ISSUE THREAD

**Issue by mar627** [statamic/workshop#30]
Easy one:

The links under the 'Tags' section that navigate the user throughout the docs on:
https://statamic.com/marketplace/addons/workshop/docs
Are missing corresponding id's! I click them every other day and wait, cursing my isp.

Current:
`<h3>Entry:Create</h3>`

Ideal:
`<h3 id="entrycreate">Entry:Create</h3>`

⭐️

**Comment by jasonvarga** [comment]
Fixed now. Click away!
