### ISSUE TITLE
I want that Statamic 3 goodness, but Workshop is holding me back

### ISSUE THREAD

**Issue by mar627** [statamic/workshop#37]
I have clients who require the workshop feature as they allow their users to create posts and pages on their site. Updating is kind of at an end now as I can't provide the perks of Statamic3 to them.. sad.

I love the ecosystem and would prefer to keep this as a statamic-only experience (opposed to linking a google form or alike). So please, give Workshop that polish it needs, it's a paid add-on after all. Maybe check out the issues in the repo and who knows rebuild ground-up. But please, promise me it's on the way, don't leave us behind gentlemen.

**Comment by jackmcdade** [comment]
You're in luck – Workshop _has_ been ported to v3 by Duncan McClean (with our permission). It's now called Guest Entries, and you can get it here: https://statamic.com/addons/double-three-digital/guest-entries
